---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
- name: freebsd-9.2
- name: freebsd-9.2-i386

suites:
- name: portsnap
  run_list:
  - recipe[freebsd::portsnap]
